# Generated by Django 5.1.15 on 2026-09-29 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'unidade',
                'verbose_name_plural': 'unidades',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo', models.CharField(blank=True, max_length=50, verbose_name='código')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pecas', to='estoque.categoria')),
            ],
            options={
                'verbose_name': 'peça',
                'verbose_name_plural': 'peças',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EstoqueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque_itens', to='estoque.peca')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque_itens', to='estoque.unidade')),
            ],
            options={
                'verbose_name': 'item de estoque',
                'verbose_name_plural': 'itens de estoque',
                'constraints': [models.UniqueConstraint(fields=('peca', 'unidade'), name='unico_peca_por_unidade')],
            },
        ),
    ]
