# Generated by Django 5.1.15 on 2026-09-29 04:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_seed_unidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='codigo_externo',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator('^\\d{1,13}$', 'Use apenas números, até 13 dígitos.')], verbose_name='código externo'),
        ),
        migrations.AddField(
            model_name='peca',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='pecas/'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, verbose_name='código interno (ref)'),
        ),
    ]
