# Generated by Django 5.1.15 on 2026-09-29 05:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa física'), ('PJ', 'Pessoa jurídica')], default='PF', max_length=2)),
                ('nome', models.CharField(max_length=200, verbose_name='nome / razão social')),
                ('documento', models.CharField(max_length=14, unique=True, verbose_name='CPF/CNPJ')),
                ('cep', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'CEP deve ter 8 dígitos.')])),
                ('logradouro', models.CharField(blank=True, max_length=200)),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('nome_representante', models.CharField(blank=True, max_length=200)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nome'],
            },
        ),
    ]
