# Generated by Django 5.1.15 on 2026-09-29 05:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='notas_fiscais/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('serie', models.CharField(blank=True, max_length=10)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('valor_produtos', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('chave_acesso', models.CharField(blank=True, max_length=44, validators=[django.core.validators.RegexValidator('^\\d{44}$', 'Chave de acesso deve ter 44 dígitos.')])),
                ('natureza_operacao', models.CharField(blank=True, max_length=200)),
                ('observacoes', models.TextField(blank=True)),
                ('texto_extraido', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'nota fiscal',
                'verbose_name_plural': 'notas fiscais',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='NotaFiscalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('ncm', models.CharField(blank=True, max_length=20)),
                ('cfop', models.CharField(blank=True, max_length=20)),
                ('unidade', models.CharField(blank=True, max_length=10)),
                ('quantidade', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='notas_fiscais.notafiscal')),
            ],
            options={
                'verbose_name': 'item da nota fiscal',
                'verbose_name_plural': 'itens da nota fiscal',
            },
        ),
    ]
