# Generated by Django 5.1.15 on 2026-09-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('notas_fiscais', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notafiscal',
            constraint=models.UniqueConstraint(condition=models.Q(('numero__gt', '')), fields=('numero',), name='notafiscal_numero_unico_quando_preenchido'),
        ),
    ]
